name: hms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    # Deploy MySQL database on Vercel
    - name: Setup MySQL on Vercel
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        mysql -h"${{ secrets.MYSQL_HOST }}" -u"${{ secrets.MYSQL_USER }}" -p"${{ secrets.MYSQL_PASSWORD }}" -e "CREATE DATABASE IF NOT EXISTS my_database;"
    
    # Deploy to Vercel and setup database
    - name: Deploy to Vercel with Snaplet
      uses: snaplet/vercel-preview-database-action@v1.0.1
      with:
        vercel-env: DATABASE_URL
        database-create-command: snaplet preview-database create --git --latest
        database-url-command: snaplet preview-database url --git
        database-reset: true  # Reset database on each commit

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
